language: android
android:
  components:
    - platform-tools
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - build-tools-28.0.0
    - android-28

before_install:
    - chmod +x gradlew

before_install:
  - yes | sdkmanager "platforms;android-28"

before_script:
    - chmod +x gradlew

script:
   - ./gradlew build connectedCheck
